import type { DiagramData } from "@/lib/beee.functions";

export function CircuitDiagram({ diagram }: { diagram: DiagramData }) {
  if (diagram.image_url) {
    return (
      <img
        src={diagram.image_url}
        alt={diagram.description}
        className="w-full max-w-lg rounded-xl border border-border bg-surface"
      />
    );
  }

  if (diagram.svg) {
    return (
      <div
        className="my-4 flex min-h-40 max-w-xl items-center justify-center overflow-x-auto rounded-xl border border-border bg-surface p-4 shadow-soft [&_svg]:h-auto [&_svg]:max-w-full"
        dangerouslySetInnerHTML={{ __html: diagram.svg }}
      />
    );
  }

  if (diagram.ascii) {
    return (
      <pre className="overflow-x-auto rounded-lg border border-border bg-surface-muted p-3 font-mono text-xs text-foreground">
        {diagram.ascii}
      </pre>
    );
  }

  if (diagram.error) {
    return (
      <div className="rounded-xl border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
        {diagram.error}
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-border bg-surface-muted p-4 text-sm text-muted-foreground text-center">
      Diagram schematic instructions are present but no SVG was generated by the backend.
    </div>
  );
}
